// Writes tests/cross_fill_normal.h: normal fills from the key of seed 42, K = 32, from the host
// code of core.hpp. f64 rows are ziggurat fills at the starts of tandem-c's tests/cross_normal.h,
// so the values are those of its CROSS_NORMAL rows byte for byte. f32 rows are Box-Muller pairs of
// uniform draws 2j and 2j + 1 of the Float32 fill, cos half first, which an odd n ends with. Run:
// make cross
#include <cstdio>
#include <initializer_list>

#include "tandem/core.hpp"

int main() {
    tandem::Rng root(42, 0, 32);
    std::printf("// Generated by tools/gen_cross_fill_normal.cpp, do not edit. Normal fills from the key of\n"
                "// seed 42 (see cross_fill_below.h), K = 32. `pos` is the start position, which the fill aligns\n"
                "// up to 64 bits (f64) or 32 bits (f32). f64: element e is the ziggurat of UInt64 draw e, at\n"
                "// the starts of tandem-c's tests/cross_normal.h, whose last rows hold misses of every kind,\n"
                "// exact on hosts and devices. f32: element 2j is the cos half and 2j + 1 the sin half of the\n"
                "// Box-Muller step of uniform draws 2j and 2j + 1, and an odd n drops the last sin half and\n"
                "// still consumes both draws, exact on hosts and to 16 ulps + 1e-6 on devices.\n"
                "#pragma once\n#include <stdint.h>\n\n");
    std::printf("typedef struct { uint64_t pos; unsigned n; double out[64]; } cross_normal64;\n"
                "static const cross_normal64 CROSS_NORMAL64[] = {\n");
    for (uint64_t pos : {0ull, 1ull, 12345ull, 4673ull, 17345ull, 2914241ull}) {
        tandem::Rng r = root;
        r.set_position(pos);
        std::printf("    {%lluull, 64, {", (unsigned long long)pos);
        for (int i = 0; i < 64; i++) std::printf("%s%.17g", i ? ", " : "", r.normal());
        std::printf("}},\n");
    }
    std::printf("};\n\ntypedef struct { uint64_t pos; unsigned n; float out[64]; } cross_normal32;\n"
                "static const cross_normal32 CROSS_NORMAL32[] = {\n");
    for (uint64_t pos : {0ull, 32ull, 64ull, 96ull, 1000ull}) {
        tandem::Rng r = root;
        r.set_position(pos);
        const size_t n = 33;
        std::printf("    {%lluull, %zu, {", (unsigned long long)pos, n);
        for (size_t j = 0; j < (n + 1) / 2; j++) {
            auto z = tandem::box_muller2_f32(r.at_frand(2 * j), r.at_frand(2 * j + 1));
            std::printf("%s%.9g", j ? ", " : "", (double)z.z0);
            if (2 * j + 1 < n) std::printf(", %.9g", (double)z.z1);
        }
        std::printf("}},\n");
    }
    std::printf("};\n");
    return 0;
}
