// Writes tests/cross_fill_below.h: bounded fills from the key of seed 42, K = 32, position 0, for
// ports to match, including the fallback stream of rejected draws. It uses only core.hpp and
// spells the contract out with Rng calls, apart from below_u32/u64 which the device code shares.
// Run: make cross
#include <cstdio>
#include <cstdlib>

#include "tandem/core.hpp"

static const size_t N = 64;

struct Counts {
    unsigned rejected = 0;
};

static uint32_t below32(const tandem::Rng &root, uint32_t range, uint64_t e, Counts &c) {
    uint32_t u = root.at_urand(e);
    uint64_t m = (uint64_t)u * range;
    if ((uint32_t)m < range) {
        uint32_t t = (0u - range) % range;
        if ((uint32_t)m < t) {
            c.rejected++;
            tandem::Rng f = root.sub(tandem::PURPOSE_BELOW32).split(e);
            do m = (uint64_t)f.urand() * range; while ((uint32_t)m < t);
        }
    }
    return (uint32_t)(m >> 32);
}

static uint64_t below64(const tandem::Rng &root, uint64_t range, uint64_t e, Counts &c) {
    uint64_t x = root.at_urand64(e), lo = x * range;
    if (lo < range) {
        uint64_t t = (0u - range) % range;
        if (lo < t) {
            c.rejected++;
            tandem::Rng f = root.sub(tandem::PURPOSE_BELOW64).split(e);
            do {
                x = f.urand64();
                lo = x * range;
            } while (lo < t);
        }
    }
    return tandem::mulhi64(x, range);
}

int main() {
    tandem::Rng root(42, 0, 32);
    tandem::Key key = root.key();
    std::printf("// Generated by tools/gen_cross_fill_below.cpp, do not edit. Bounded fills of %zu elements\n"
                "// from the key of seed 42 (key below), K = 32, position 0. Element e takes draw e of the\n"
                "// UInt32 (UInt64) fill. A rejected draw retries on the draws of split(e) of\n"
                "// sub(0x424c573332) (32-bit) or sub(0x424c573634) (64-bit), from position 0.\n"
                "// `rejected` counts the elements that took the fallback.\n"
                "#pragma once\n#include <stdint.h>\n\n",
                N);
    std::printf("static const uint32_t CROSS_FILL_KEY[4] = {0x%08xu, 0x%08xu, 0x%08xu, 0x%08xu};\n\n",
                key.w[0], key.w[1], key.w[2], key.w[3]);
    const uint32_t r32[] = {3u, 7u, 10u, 1000u, 0x80000001u, 0xffffffffu};
    const uint64_t r64[] = {3ull, 7ull, 10ull, 1000ull, 0x80000001ull, 0xffffffffull,
                            0x8000000000000001ull, 0xffffffffffffffffull};
    unsigned total32 = 0, total64 = 0;
    std::printf("typedef struct { uint32_t range; unsigned rejected; uint32_t out[%zu]; } cross_below32;\n"
                "static const cross_below32 CROSS_BELOW32[] = {\n", N);
    for (uint32_t r : r32) {
        Counts c;
        uint32_t v[N];
        for (size_t e = 0; e < N; e++) v[e] = below32(root, r, e, c);
        total32 += c.rejected;
        std::printf("    {%uu, %u, {", r, c.rejected);
        for (size_t e = 0; e < N; e++) std::printf("%s%uu", e ? ", " : "", v[e]);
        std::printf("}},\n");
    }
    std::printf("};\n\ntypedef struct { uint64_t range; unsigned rejected; uint64_t out[%zu]; } cross_below64;\n"
                "static const cross_below64 CROSS_BELOW64[] = {\n", N);
    for (uint64_t r : r64) {
        Counts c;
        uint64_t v[N];
        for (size_t e = 0; e < N; e++) v[e] = below64(root, r, e, c);
        total64 += c.rejected;
        std::printf("    {%lluull, %u, {", (unsigned long long)r, c.rejected);
        for (size_t e = 0; e < N; e++) std::printf("%s%lluull", e ? ", " : "", (unsigned long long)v[e]);
        std::printf("}},\n");
    }
    std::printf("};\n");
    if (!total32 || !total64) {
        std::fprintf(stderr, "no rejection exercised\n");
        return 1;
    }
    return 0;
}
