// Writes tests/cross_fill_exponential.h: exponential fills from the key of seed 42, K = 32, by
// core.hpp's exponential_f64 and exponential_f32, which run tandem-c's polynomial logarithm on
// every host and device. Ports with that code match exactly. Run: make cross
#include <cstdio>
#include <initializer_list>

#include "tandem/core.hpp"

int main() {
    const tandem::Rng root(42, 0, 32);
    const unsigned n = 33;
    std::printf("// Generated by tools/gen_cross_fill_exponential.cpp, do not edit. Exponential fills from\n"
                "// the key of seed 42 (see cross_fill_below.h), K = 32. `pos` is the start position, which the\n"
                "// fill aligns up to 64 bits (f64) or 32 bits (f32). Element i is -ln(1 - u) of uniform draw i.\n"
                "// Every host and device build matches exactly.\n"
                "#pragma once\n#include <stdint.h>\n\n");
    std::printf("typedef struct { uint64_t pos; unsigned n; double out[64]; } cross_exp64;\n"
                "static const cross_exp64 CROSS_EXP64[] = {\n");
    for (uint64_t pos : {0ull, 1ull, 77ull, 12345ull, 1ull << 30}) {
        tandem::Rng r = root;
        r.set_position(pos);
        std::printf("    {%lluull, %u, {", (unsigned long long)pos, n);
        for (unsigned i = 0; i < n; i++)
            std::printf("%s%.17g", i ? ", " : "", tandem::exponential_f64(r.at_drand(i)));
        std::printf("}},\n");
    }
    std::printf("};\n\ntypedef struct { uint64_t pos; unsigned n; float out[64]; } cross_exp32;\n"
                "static const cross_exp32 CROSS_EXP32[] = {\n");
    for (uint64_t pos : {0ull, 1ull, 77ull, 12345ull, 1ull << 30}) {
        tandem::Rng r = root;
        r.set_position(pos);
        std::printf("    {%lluull, %u, {", (unsigned long long)pos, n);
        for (unsigned i = 0; i < n; i++)
            std::printf("%s%.9gf", i ? ", " : "", (double)tandem::exponential_f32(r.at_frand(i)));
        std::printf("}},\n");
    }
    std::printf("};\n");
    return 0;
}
