// Writes tests/cross_fill_normal.h: normal fills from the key of seed 42, K = 32, from the host
// Box-Muller of core.hpp, which equals tandem-c's bit for bit. Ports with that polynomial code
// match exactly. Device f32 fills use the device's sincos and match to a few ulps. Pair j of a fill is one Box-Muller step of uniform draws 2j and 2j + 1 of
// the Float64 (Float32) fill, cos half first, so element 2j is the cos half and 2j + 1 the sin
// half. An odd n drops the last sin half. Run: make cross
#include <cstdio>
#include <initializer_list>

#include "tandem/core.hpp"

template <class T, class Step, class Draw>
static void emit(const char *name, const char *fmt, unsigned w, uint64_t pos, size_t n, Step step,
                 Draw draw) {
    size_t np = (n + 1) / 2;
    std::printf("    {%lluull, %zu, {", (unsigned long long)pos, n);
    (void)name;
    for (size_t j = 0; j < np; j++) {
        auto z = step(draw(2 * j), draw(2 * j + 1));
        std::printf("%s", j ? ", " : "");
        std::printf(fmt, (double)z.z0);
        if (2 * j + 1 < n) {
            std::printf(", ");
            std::printf(fmt, (double)z.z1);
        }
    }
    std::printf("}},\n");
    (void)w;
}

int main() {
    tandem::Rng root(42, 0, 32);
    std::printf("// Generated by tools/gen_cross_fill_normal.cpp, do not edit. Normal fills from the key of\n"
                "// seed 42 (see cross_fill_below.h), K = 32. `pos` is the start position, which the fill aligns\n"
                "// up to 64 bits (f64) or 32 bits (f32). Element 2j is the cos half and 2j + 1 the sin half of\n"
                "// the Box-Muller step of uniform draws 2j and 2j + 1. An odd n drops the last sin half and\n"
                "// still consumes both draws. From the host polynomial Box-Muller of core.hpp and tandem-c:\n"
                "// f64 matches exactly on hosts and devices, f32 exactly on hosts and to 16 ulps + 1e-6 on\n"
                "// devices.\n"
                "#pragma once\n#include <stdint.h>\n\n");
    std::printf("typedef struct { uint64_t pos; unsigned n; double out[64]; } cross_normal64;\n"
                "static const cross_normal64 CROSS_NORMAL64[] = {\n");
    for (uint64_t pos : {0ull, 64ull, 1000ull}) {
        tandem::Rng r = root;
        r.set_position(pos);
        emit<double>("f64", "%.17g", 64, pos, 33, tandem::box_muller2,
                     [&](size_t i) { return r.at_drand(i); });
    }
    std::printf("};\n\ntypedef struct { uint64_t pos; unsigned n; float out[64]; } cross_normal32;\n"
                "static const cross_normal32 CROSS_NORMAL32[] = {\n");
    for (uint64_t pos : {0ull, 32ull, 64ull, 96ull, 1000ull}) {
        tandem::Rng r = root;
        r.set_position(pos);
        emit<float>("f32", "%.9g", 32, pos, 33, tandem::box_muller2_f32,
                    [&](size_t i) { return r.at_frand(i); });
    }
    std::printf("};\n");
    return 0;
}
