#!/usr/bin/env python3
"""Turn the spec's ziggurat tables into include/tandem/normal_tables.hpp, value for value.

Usage: tools/gen_normal_tables.py path/to/normal_f64_zig1024.json > include/tandem/normal_tables.hpp
"""
import hashlib
import json
import sys

SHA256 = "8b961dd46a2582b953bd8780138edb0ad712e3d243a366a123ffc8978d0a33ab"


def rows(items, per_line=4):
    lines = []
    for i in range(0, len(items), per_line):
        lines.append("    " + ", ".join(items[i : i + per_line]) + ", \\")
    return "\n".join(lines)


def hexf(s):
    x = float.fromhex(s)
    assert x.hex() == float.fromhex(x.hex()).hex()
    return x.hex()


def main(path):
    raw = open(path, "rb").read()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != SHA256:
        sys.exit(f"{path}: SHA-256 {digest}, expected {SHA256}")
    t = json.loads(raw)
    n = t["layers"]
    assert n == 1024 and len(t["W"]) == n and len(t["K"]) == n and len(t["Y"]) == n + 1
    assert all(0 <= k < 2**53 for k in t["K"]) and t["K"][-1] == 0
    wk = [f"{{{hexf(w)}, {k}ull}}" for w, k in zip(t["W"], t["K"])]
    y = [hexf(s) for s in t["Y"]]
    assert float.fromhex(y[-1]) == 1.0
    print(f"""/* Generated by tools/gen_normal_tables.py from tandem-spec tables/normal_f64_zig1024.json,
 * SHA-256 {SHA256}. Do not edit.
 *
 * The 1024-layer ziggurat of the Float64 normals (spec Appendix A): R, the width W[i] and the
 * threshold K[i] of layer i side by side, so that the fast path reads one 16-byte entry, and the
 * heights Y. Device passes read copies in global memory. */
#pragma once

#include <cstdint>

#define TANDEM_ZIG_WK {{ \\
{rows(wk, 2)}
    }}
#define TANDEM_ZIG_Y {{ \\
{rows(y)}
    }}

namespace tandem {{
namespace zig {{

struct alignas(16) Layer {{
    double w;
    uint64_t k;
}};

constexpr double R = {hexf(t["R"])};
inline constexpr Layer WK[{n}] = TANDEM_ZIG_WK;
inline constexpr double Y[{n + 1}] = TANDEM_ZIG_Y;

#if defined(__CUDACC__) || defined(__HIPCC__)
static __device__ const Layer WK_DEVICE[{n}] = TANDEM_ZIG_WK;
static __device__ const double Y_DEVICE[{n + 1}] = TANDEM_ZIG_Y;
#endif

}} // namespace zig
}} // namespace tandem

#undef TANDEM_ZIG_WK
#undef TANDEM_ZIG_Y""")


if __name__ == "__main__":
    main(sys.argv[1])
