// Writes tests/cross_fill_below.h: bounded fills from the key of seed 42, K = 32, for ports to
// match, including the fallback stream of rejected draws. It uses only core.hpp and spells the
// contract out with Rng calls.
// Run: make cross
#include <cstdio>
#include <cstdlib>

#include "tandem/core.hpp"

static const size_t N = 64;
// tandem-c's tests/cross_fill_below.h starts, in bits. Both align up, so draw g is not element e.
static const uint64_t STARTS[] = {1, 12345};

// Element e of a fill takes draw g = align(start, w) / w + e of root, the generator at
// position 0, and a rejected draw retries on split(g) of the purpose's sub.
static uint32_t below32(const tandem::Rng &root, uint32_t range, uint64_t g, unsigned &rejected) {
    uint64_t m = (uint64_t)root.at_urand(g) * range;
    if ((uint32_t)m < range) {
        uint32_t t = (0u - range) % range;
        if ((uint32_t)m < t) {
            rejected++;
            tandem::Rng f = root.sub(tandem::PURPOSE_BELOW32).split(g);
            do m = (uint64_t)f.urand() * range; while ((uint32_t)m < t);
        }
    }
    return (uint32_t)(m >> 32);
}

static uint64_t below64(const tandem::Rng &root, uint64_t range, uint64_t g, unsigned &rejected) {
    uint64_t x = root.at_urand64(g), lo = x * range;
    if (lo < range) {
        uint64_t t = (0u - range) % range;
        if (lo < t) {
            rejected++;
            tandem::Rng f = root.sub(tandem::PURPOSE_BELOW64).split(g);
            do {
                x = f.urand64();
                lo = x * range;
            } while (lo < t);
        }
    }
    return tandem::mulhi64(x, range);
}

static const uint32_t R32[] = {3u, 7u, 10u, 1000u, 0x80000001u, 0xffffffffu};
static const uint64_t R64[] = {3ull, 7ull, 10ull, 1000ull, 0x80000001ull, 0xffffffffull,
                               0x8000000000000001ull, 0xffffffffffffffffull};

// One row per range: `{start, ` when at_start, then range, rejected count and the 64 values.
static unsigned rows32(const tandem::Rng &root, uint64_t start, bool at_start) {
    unsigned total = 0;
    uint64_t g0 = tandem::align_pos(start, 32) / 32;
    for (uint32_t r : R32) {
        unsigned rejected = 0;
        uint32_t v[N];
        for (size_t e = 0; e < N; e++) v[e] = below32(root, r, g0 + e, rejected);
        total += rejected;
        std::printf("    {");
        if (at_start) std::printf("%lluull, ", (unsigned long long)start);
        std::printf("%uu, %u, {", r, rejected);
        for (size_t e = 0; e < N; e++) std::printf("%s%uu", e ? ", " : "", v[e]);
        std::printf("}},\n");
    }
    return total;
}

static unsigned rows64(const tandem::Rng &root, uint64_t start, bool at_start) {
    unsigned total = 0;
    uint64_t g0 = tandem::align_pos(start, 64) / 64;
    for (uint64_t r : R64) {
        unsigned rejected = 0;
        uint64_t v[N];
        for (size_t e = 0; e < N; e++) v[e] = below64(root, r, g0 + e, rejected);
        total += rejected;
        std::printf("    {");
        if (at_start) std::printf("%lluull, ", (unsigned long long)start);
        std::printf("%lluull, %u, {", (unsigned long long)r, rejected);
        for (size_t e = 0; e < N; e++) std::printf("%s%lluull", e ? ", " : "", (unsigned long long)v[e]);
        std::printf("}},\n");
    }
    return total;
}

int main() {
    tandem::Rng root(42, 0, 32);
    tandem::Key key = root.key();
    std::printf("// Generated by tools/gen_cross_fill_below.cpp, do not edit. Bounded fills of %zu elements\n"
                "// from the key of seed 42 (key below), K = 32. Element e takes draw g of the UInt32\n"
                "// (UInt64) stream, g = align(start, w) / w + e for the draw width w. A rejected draw retries\n"
                "// on the draws of split(g) of sub(0x424c573332) (32-bit) or sub(0x424c573634) (64-bit) of\n"
                "// the generator at position 0. CROSS_BELOW32 and CROSS_BELOW64 start at position 0, where\n"
                "// g = e. The _AT arrays start at the bit positions in their first field, where g != e.\n"
                "// `rejected` counts the elements that took the fallback.\n"
                "#pragma once\n#include <stdint.h>\n\n",
                N);
    std::printf("static const uint32_t CROSS_FILL_KEY[4] = {0x%08xu, 0x%08xu, 0x%08xu, 0x%08xu};\n\n",
                key.w[0], key.w[1], key.w[2], key.w[3]);
    unsigned total32 = 0, total64 = 0, at32 = 0, at64 = 0;
    std::printf("typedef struct { uint32_t range; unsigned rejected; uint32_t out[%zu]; } cross_below32;\n"
                "static const cross_below32 CROSS_BELOW32[] = {\n", N);
    total32 += rows32(root, 0, false);
    std::printf("};\n\ntypedef struct { uint64_t range; unsigned rejected; uint64_t out[%zu]; } cross_below64;\n"
                "static const cross_below64 CROSS_BELOW64[] = {\n", N);
    total64 += rows64(root, 0, false);
    std::printf("};\n\ntypedef struct { uint64_t start; uint32_t range; unsigned rejected; uint32_t out[%zu]; } cross_below32_at;\n"
                "static const cross_below32_at CROSS_BELOW32_AT[] = {\n", N);
    for (uint64_t s : STARTS) at32 += rows32(root, s, true);
    std::printf("};\n\ntypedef struct { uint64_t start; uint64_t range; unsigned rejected; uint64_t out[%zu]; } cross_below64_at;\n"
                "static const cross_below64_at CROSS_BELOW64_AT[] = {\n", N);
    for (uint64_t s : STARTS) at64 += rows64(root, s, true);
    std::printf("};\n");
    if (!total32 || !total64 || !at32 || !at64) {
        std::fprintf(stderr, "no rejection exercised\n");
        return 1;
    }
    return 0;
}
